[package]
name = 'MsBackendMzPeak'
publish = false
version = '0.1.0'
edition = '2021'
rust-version = '1.65'

[lib]
crate-type = [ 'rlib', 'staticlib' ]
name = 'MsBackendMzPeak'

[[bin]]
name = 'document'
path = 'document.rs'

[dependencies]
extendr-api = '*'
mzdata = "0.64.1"
mzpeak_prototyping = { git = "https://github.com/HUPO-PSI/mzPeak.git" }
parquet = { version = "57.0.0", features = ["encryption"] }
rayon = "1"

[profile.release]
lto = true
codegen-units = 1
