# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib MsBackendMzPeak, .registration = TRUE
NULL

#' Read an the spectrum of a mzPeak archive.
#'
#' @param filename `character(1)` Path to the mzPeak archive.
#'
#' @param index optional `integer` with the index of the Spectrum to extract.
#'     If not provided, the function extract all the Spectrum.
#'
#' @return `list` containing the spectra data.
#'
#' @author Gabriele Tomè
#'
#' @noRd
mzpeak_read_peaks <- function(path, index) .Call(wrap__mzpeak_read_peaks, path, index)

#' Read an the peaks of a mzPeak archive.
#'
#' @param filename `character(1)` Path to the mzPeak archive.
#'
#' @return `data.frame` containing the spectra data.
#'
#' @author Gabriele Tomè
#'
#' @noRd
mzpeak_read_all_peaks <- function(path) .Call(wrap__mzpeak_read_all_peaks, path)

#' Function to read spectrum metadata fields of a mzPeak file.
#'
#' @param filename Path to the mzPeak archive.
#'
#' @return `list` containing the matadate of the spectra.
#'
#' @author Gabriele Tomè
#'
#' @noRd
mzpeak_read_all_spectrum_metadata <- function(path) .Call(wrap__mzpeak_read_all_spectrum_metadata, path)

#' Function to convert files to mzPeak
#'
#' @param filename `character(1)` Path to the file to convert.
#'
#' @param outfile `character(1)` Path where save the mzPeak archive.
#'
#' @author Gabriele Tomè, Joshua Klein
#'
#' @noRd
mzpeak_convert <- function(filename, outfile) .Call(wrap__mzpeak_convert, filename, outfile)

#' Function to read sample metadata `FileIndex` of a mzPeak file.
#'
#' @param filename Path to the mzPeak archive.
#'
#' @author Gabriele Tomè
#'
#' @noRd
mzpeak_read_sample_metadata <- function(path) .Call(wrap__mzpeak_read_sample_metadata, path)

#' Function to read File Description fields of  metadata `FileIndex` of a
#' mzPeak file.
#'
#' @param filename Path to the mzPeak archive.
#'
#' @author Gabriele Tomè
#'
#' @noRd
mzpeak_read_file_description <- function(path) .Call(wrap__mzpeak_read_file_description, path)

#' Function to read File Description fields of  metadata `FileIndex` of a
#' mzPeak file.
#'
#' @param filename Path to the mzPeak archive.
#'
#' @author Gabriele Tomè
#'
#' @noRd
mzpeak_read_software <- function(path) .Call(wrap__mzpeak_read_software, path)

# nolint end
