# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib MsBackendMzPeak, .registration = TRUE
NULL

#' Read an mzPeak archive and return the number of spectra and total number of
#' points.
#'
#' @param filename `character(1)` Path to the mzPeak archive.
#'
#' @param encryption_key `character(1)` Optional AES decryption key (16, 24,
#'     or 32 bytes).
#'
#' @return `list` containing the number of spectra and the number of points in
#'
#' @author Gabriele Tomè
#'
#' @noRd
mzpeak_info <- function(filename, encryption_key = NULL) .Call(wrap__mzpeak_info, filename, encryption_key)

#' Function to read description field of a mzPeak file.
#'
#' @param filename Path to the mzPeak archive.
#'
#' @param encryption_key `character(1)` Optional AES decryption key (16, 24,
#'     or 32 bytes).
#'
#' @param index optional `integer` with the index of the SpectrumDescription
#'
#' @return `list` containing the matadate of the spectra.
#'
#' @author Gabriele Tomè
#'
#' @noRd
mzpeak_read_desc <- function(filename, encryption_key = NULL, index = NULL) .Call(wrap__mzpeak_read_desc, filename, encryption_key, index)

#' Read an the spectrum of a mzPeak archive.
#'
#' @param filename `character(1)` Path to the mzPeak archive.
#'
#' @param encryption_key `character(1)` Optional AES decryption key (16, 24,
#'     or 32 bytes).
#'
#' @param index optional `integer` with the index of the Spectrum to extract.
#'     If not provided, the function extract all the Spectrum.
#'
#' @return `list` of `data.frame` containing the spectra data.
#'
#' @author Gabriele Tomè
#'
#' @noRd
mzpeak_read_spectrum <- function(filename, encryption_key = NULL, index = NULL) .Call(wrap__mzpeak_read_spectrum, filename, encryption_key, index)

#' Read an the peaks of a mzPeak archive.
#'
#' @param filename `character(1)` Path to the mzPeak archive.
#'
#' @param encryption_key `character(1)` Optional AES decryption key (16, 24,
#'     or 32 bytes).
#'
#' @param index optional `integer` with the index of the Spectrum to extract.
#'     If not provided, the function extract all the Spectrum.
#'
#' @return `list` of `data.frame` containing the spectra data.
#'
#' @author Gabriele Tomè
#'
#' @noRd
mzpeak_read_peaks <- function(filename, encryption_key = NULL, index = NULL) .Call(wrap__mzpeak_read_peaks, filename, encryption_key, index)

# nolint end
